### ISSUE TITLE
Self testing failed for Objective-C

### ISSUE THREAD

**Issue by heeyoung-choi** [DMOJ/judge-server#1201]
After running `docker run -v /mnt/problems:/problems --cap-add=SYS_PTRACE dmoj/judge-tier1:latest cli -c /problems/judge.yml`
i'm getting this log:
 ```
Self-testing executors
Self-testing AWK:    Success [0.003s, 2316 KB]   awk 1.3.4
Self-testing C:      Success [0.002s, 1008 KB]   gcc 14
Self-testing CPP03:  Success [0.003s, 1988 KB]   g++ 14
Self-testing CPP11:  Success [0.003s, 2072 KB]   g++11 14
Self-testing JAVA:   Success [0.109s, 39248 KB]  javac 1.8.0
Self-testing OBJC:   Failed
Traceback (most recent call last):
  File "/judge/dmoj/executors/base_executor.py", line 343, in run_self_test
    executor = cls(cls.test_name, utf8bytes(cls.test_program))
  File "/judge/dmoj/executors/compiled_executor.py", line 66, in __call__
    obj.compile()
    ~~~~~~~~~~~^^
  File "/judge/dmoj/executors/compiled_executor.py", line 227, in compile
    process = self.create_compile_process(self.get_compile_args())
                                          ~~~~~~~~~~~~~~~~~~~~~^^
  File "/judge/dmoj/executors/c_like_executor.py", line 76, in get_compile_args
    + self.get_flags()
      ~~~~~~~~~~~~~~^^
  File "/judge/dmoj/executors/OBJC.py", line 30, in get_flags
    return self.runtime_dict['objc_flags'] + super().get_flags()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
Self-testing PERL:   Success [0.007s, 5908 KB]   perl 5.40.0
Self-testing SED:    Success [0.003s, 1228 KB]   sed 4.9

Running local judge...

```
This is my judge.yml
```
# This is the same ID you specified in the judge admin panel.
id: Test1
# The key this judge will use to authenticate with the site server, generated from the admin panel.
key: "s98+gauBD+Ci0UeIagQ4CTAdepLsHCNo37Zl5RUCFDVyUlOHpFn/kkV+8+N4FqXhQFNudOAI1j0Dv4ll4BvEIu1UIwGHVZSx9qam"
# Where to look for problems on the local filesystem.
# Any directory matching any of the following globs with an init.yml file is assumed to be a problem directory.
problem_storage_globs:
  # - /mnt/problems/folder1/*  # matches /mnt/problems/folder1/<problem>
  # - /mnt/problems/folder2/**/  # matches any subfolder of /mnt/problems/folder2
  # - /mnt/problems/folder3/year20[0-9][0-9]  # matches /mnt/problems/folder3/year2023, for example
  - /home/opc/judge/testsuite/*
  -  /home/opc/judge/testsuite/**/
# All configuration for language executors.
# If you're unsure of what values a language needs, your best bet is to consult the source of the executor:
# <https://github.com/DMOJ/judge-server/tree/master/dmoj/executors>
runtime:
  ccl: /opt/ccl/lx86cl
  sed: /bin/sed
  awk: /usr/bin/awk
  gnatmake: /usr/bin/gnatmake
  chicken-csc: /usr/bin/csc
  dart: /opt/dart-sdk/bin/dart
  tclsh: /usr/bin/tclsh
  cobc: /usr/bin/cobc
  erl: /usr/bin/erl
  erlc: /usr/bin/erlc
  tprolog: /opt/turing/tprolog/tprolog
  tprologc: /opt/turing/tprolog/tprologc
  turing_dir: /opt/turing/tprolog
  node: /usr/bin/node
  lua: /usr/bin/lua
  ocaml: /usr/bin/ocamlopt
  pypy: /opt/pypy/bin/pypy
  pypydir: /opt/pypy/
  pypy3: /opt/pypy3/bin/pypy
  pypy3dir: /opt/pypy3/
  ghc: /usr/bin/ghc
  go: /usr/bin/go
  fsharpc: /usr/bin/fsharpc
  mono-csc: /usr/bin/mono-csc
  mono-vbnc: /usr/bin/vbnc
  mono: /usr/bin/mono
  dmd: /usr/bin/dmd
  fpc: /opt/fpc-2.6.4/bin/fpc
  clang: /usr/bin/clang
  clang++: /usr/bin/clang++
  gcc: /usr/bin/gcc
  g++: /usr/bin/g++
  g++11: /usr/bin/g++
  g++14: /opt/gcc-5.1.0/bin/g++
  gfortran: /usr/bin/gfortran
  nasm: /usr/bin/nasm
  ld: /usr/bin/ld
  python: /opt/python27/bin/python2.7
  python2dir: /opt/python27/
  python3: /opt/python34/bin/python3.4
  python3dir: /opt/python34/
  java: /usr/bin/java
  javac: /usr/bin/javac
  java8: /usr/lib/jvm/jdk-8-oracle-i586/bin/java
  javac8: /usr/lib/jvm/jdk-8-oracle-i586/bin/javac
# Custom V8 build to facilitate online judging: https://github.com/DMOJ/v8dmoj
  v8dmoj: /home/judge/judge/executors/v8dmoj
  php: /usr/bin/php
  phpconfdir: /etc/php5/
  perl: /usr/bin/perl
  ruby19: /usr/bin/ruby1.9.1
  ruby21: /usr/bin/ruby
  racket: /opt/racket/bin/racket
  raco: /opt/racket/bin/raco
  racket-lib: /opt/racket/lib
  gnustep-config: /usr/bin/gnustep-config
  gobjc: /usr/bin/gcc
```
