### ISSUE TITLE
Problem validation mode for `dmoj-cli`

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge-server#335]
In particular, we should allow declarations of `test` fields in `init.yml` structured like so:

```yaml
tests: [
   {
        label: "A Correct Solution", // optional
        source: sol.py,
        lang: PY2, // optional, can infer
        timelimit: 2,
        memlimit: 65536,
        expected: AC,
        targets: [linux, freebsd, windows], // optional, default to all
   }
]
```

This can reuse some of the heavy lifting of the current testsuite implementation, and should be invokable after #334 by `dmoj-cli -- validate $PROBLEM_CODE`.
